from datetime import datetime
from typing import Any, List, Optional
import uuid

from pydantic import BaseModel, ConfigDict, Field

from app.models.enums import ExtractionStatus, ProcessingStatus


# =============================================================================
# LLM Structured Output Parsing Schemas
# =============================================================================


class LLMExtractedFieldItem(BaseModel):
    """Raw structured field item generated by the extraction LLM."""

    field_name: str = Field(..., description="Registered field name")
    value: Optional[str] = Field(None, description="Extracted textual value or null if not found")
    confidence: float = Field(default=0.0, ge=0.0, le=1.0, description="Extraction confidence score 0.0 - 1.0")
    page_number: int = Field(default=1, ge=1, description="1-indexed source document page number")
    source_text: str = Field(default="", description="Exact supporting snippet from OCR text")
    bounding_box: Optional[dict[str, Any]] = Field(None, description="Optional bounding box coordinates")


class LLMExtractionOutput(BaseModel):
    """Container schema for structured LLM extraction output."""

    fields: List[LLMExtractedFieldItem] = Field(default_factory=list, description="List of extracted candidate fields")


# =============================================================================
# API Response Schemas
# =============================================================================


class ExtractedFieldResponse(BaseModel):
    """Structured property field representation."""

    id: uuid.UUID = Field(..., description="Extracted field unique UUID")
    document_id: uuid.UUID = Field(..., description="Document UUID")
    field_name: str = Field(..., description="Schema field identifier")
    field_value: Optional[str] = Field(None, description="Raw extracted value as written in document")
    normalized_value: Optional[str] = Field(None, description="Conservative normalized value representation")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Extraction confidence score (0.0 - 1.0)")
    status: ExtractionStatus = Field(..., description="Extraction outcome status ('extracted', 'uncertain', 'not_found')")
    extractor_version: str = Field(..., description="Extractor pipeline version")
    created_at: datetime = Field(..., description="Extraction timestamp")

    model_config = ConfigDict(from_attributes=True)


class DocumentExtractionResponse(BaseModel):
    """Document structured extraction summary response."""

    document_id: uuid.UUID = Field(..., description="Document UUID")
    status: str = Field(..., description="Overall extraction processing status")
    fields: List[ExtractedFieldResponse] = Field(default_factory=list, description="Extracted field candidates")

    model_config = ConfigDict(from_attributes=True)


class EvidenceItemResponse(BaseModel):
    """Individual source page evidence reference."""

    id: uuid.UUID = Field(..., description="Evidence reference UUID")
    page_number: int = Field(..., ge=1, description="1-indexed source page number")
    source_text: str = Field(..., description="Exact textual excerpt grounded in OCR text")
    bounding_box: Optional[dict[str, Any]] = Field(None, description="Visual coordinate region if present")
    created_at: datetime = Field(..., description="Evidence recording timestamp")

    model_config = ConfigDict(from_attributes=True)


class FieldEvidenceGroupResponse(BaseModel):
    """Extracted field paired with its grounded evidence citations."""

    field_name: str = Field(..., description="Field identifier")
    field_value: Optional[str] = Field(None, description="Raw extracted value")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Extraction confidence score")
    status: ExtractionStatus = Field(..., description="Extraction status")
    evidence: List[EvidenceItemResponse] = Field(default_factory=list, description="Grounded source citations")

    model_config = ConfigDict(from_attributes=True)


class DocumentEvidenceResponse(BaseModel):
    """Complete evidence audit dossier linking extracted fields to document pages."""

    document_id: uuid.UUID = Field(..., description="Document UUID")
    fields: List[FieldEvidenceGroupResponse] = Field(default_factory=list, description="Grounded field extractions")

    model_config = ConfigDict(from_attributes=True)


class ExtractionJobResponse(BaseModel):
    """Response returned upon submitting a document for background field extraction."""

    document_id: uuid.UUID = Field(..., description="Target document UUID")
    job_id: uuid.UUID = Field(..., description="Queued extraction job UUID")
    status: ProcessingStatus = Field(..., description="Extraction job execution status")

    model_config = ConfigDict(from_attributes=True)
